#!bin/bash
#This will be a basic markup of a named/bind server setup on a system
#I may create a version of this to be a slave as well, tbd

clear
echo "WARNING: DO NOT RUN THIS SCRIPT WITHOUT A VALID STATIC IP SET"
echo ""
sleep 1
echo "Please ensure that you are a sudoer or root user before continuing! (CTRL+C to exit)"
sleep 1
read -p "Press Enter to continue"

#Ask for variables here

echo "Please input your first and last initials"
read initials

echo "Please input your client machine IP"
read clientip
cip=`echo "$clientip" | sed 's/^.*\.\([^.]*\)$/\1/'`

echo "Please input your named/bind server machine IP"
read serverip
sip=`echo "$serverip" | sed 's/^.*\.\([^.]*\)$/\1/'`

echo "Please input your default gateway"
read defaultgateway

echo "Please input your desired zone name"
read zonename

clear

echo "You have entered the following information:"
echo "Initials are: $initials"
echo "Client IP is: $clientip"
echo "Server IP is: $serverip"
echo "Default gateway is $defaultgateway"
echo "Zone name is: $zonename"
echo ""
echo "If everything above is correct, press Enter. If not, CTRL+C out and start the script again"
sleep 2
read -p "Press Enter to continue"




#Now we start with the installation and whatnot.
echo "Beginning installation of bind and bindutils"
sleep 3
yum install bind bind-utils -y

echo "Starting, enabling, and checking status of process"
sleep 3
#Start and enable named services using systemctl
systemctl start named
systemctl enable named
#Status to make sure we're up and running
systemctl status named


#vi /etc/named.conf setup
#Copy original
cp /etc/named.conf /etc/named.conf.bak

#set up a premade file to push through a named.conf rather than appending or printing

cp ./masternamed.conf > /etc/masternamed.conf
echo 'include "/etc/masternamed.conf";' >> /etc/named.conf


#now we create our zone files in /var/named/
#Make changes to and copy over /var/named/forward.placeholder.db - forward lookup zone
cp ./forward.placeholder.db /var/named/forward.$namezone.db
sed 's/initials/$initials' ./forward.placeholder.db > /var/named/forward.$zonename.db
sed 's/clientip/$clientip' /var/named/forward.$zonename.db

#Make copy over and make changes to /var/named/1.168.192.db - reverse lookup zone
cp ./1.168.192.db /var/named/1.168.192.db
sed 's/initials/$initials' ./1.168.192.db > /var/named/1.168.192.db
sed 's/clientip/$cip' /var/named/1.168.192.db
sed 's/serverip/$sip' /var/named/1.168.192.db
sed 's/defaultgateway/$defaultgateway' /var/named/1.168.192.db



#now we restart bind server
systemctl restart named.service



#set nameserver in client /etc/resolv.conf

#Test using dig command

dig www.google.com
sleep 5
clear

echo "Thank you for using my script!"
sleep 10
clear
