#!bin/bash
#This will be a basic markup of a named/bind server setup on a system
#I may create a version of this to be a slave as well, tbd

echo "Please ensure that you are a sudoer or root user before continuing!"
sleep 1
read -p "Press Enter to continue"

#Ask for variables here

echo "Please input your initials"
read initials

echo "Please input your client machine IP"
read clientip

echo "Please input your named/bind server machine IP"
read serverip

echo "Please input your desired zone name"
read zonename

clear

echo "You have entered the following information:
echo "$initials"
echo "$clientip"
echo "$serverip"
echo "$zonename"
echo ""
echo "If everything above is correct, press Enter. If not, CTRL+C out and start again"
read -p "Press Enter to continue"



#Now we start with the installation and whatnot.

yum install bind bindutils -y


#Start and enable named services using systemctl
#status to make sure we're up and running




#vi /etc/named.conf setup
#Copy original? Comment out listen-*?
#consider setting up a premade file to push through a named.conf rather than appending or printing




#forward and reverse lookup zones must be referenced here

#forward
zone "placeholder.local" IN {
type master;
file "forward.placeholder.db";
allow-update { none; };
};

#reverse
zone "1.168.192.in-addr.arpa" IN {
type master;
file "1.168.192.db";
allow-update { none; };
};




#now we create our zone files in /var/named/
#vi /var/named/forward.placeholder.db
#vi /var/named/1.168.192.db - reverse lookup zone


#NOTE: IF we can create premade zone files with small inserts, we can avoid checking zone files, seeing as they'd be prebuilt and pre-tested



#now we restart bind server
#systemctl restart named.service





#at this point we can set nameserver in client /etc/resolv.conf

#Test using dig command
