#!bin/bash
#This will be a basic markup of a named/bind server setup on a system
#I may create a version of this to be a slave as well, tbd

echo "Please ensure that you are a sudoer or root user before continuing!"
sleep 1
read -p "Press Enter to continue"

#Ask for variables here

echo "Please input your initials"
read initials

echo "Please input your client machine IP"
read clientip

echo "Please input your named/bind server machine IP"
read serverip

echo "Please input your default gateway"
read defaultgateway

echo "Please input your desired zone name"
read zonename

clear

echo "You have entered the following information:
echo "Initials are: $initials"
echo "Client IP is: $clientip"
echo "Server IP is: $serverip"
echo "Default gateway is $defaultgateway"
echo "Zone name is: $zonename"
echo ""
echo "If everything above is correct, press Enter. If not, CTRL+C out and start again"
read -p "Press Enter to continue"



#Now we start with the installation and whatnot.
echo "Beginning installation of bind and bindutils"
sleep 1
yum install bind bindutils -y

echo "Starting, enabling, and checking status of process"
sleep 1
#Start and enable named services using systemctl
systemctl start named
systemctl enable named
#Status to make sure we're up and running
systemctl status named


#vi /etc/named.conf setup
#Copy original
cp /etc/named.conf /etc/named.conf.bak

#consider setting up a premade file to push through a named.conf rather than appending or printing


#forward and reverse lookup zones must be referenced here

#forward
zone "$zonename.local" IN {
type master;
file "forward.$zonename.db";
allow-update { none; };
};

#reverse
zone "1.168.192.in-addr.arpa" IN {
type master;
file "1.168.192.db";
allow-update { none; };
};




#now we create our zone files in /var/named/
#vi /var/named/forward.placeholder.db
sed 's/initials/$initials' ./forward.placeholder.db > /var/named/forward.$zonename.db
sed 's/clientip/$clientip' /var/named/forward.$zonename.db

#vi /var/named/1.168.192.db - reverse lookup zone
sed 's/initials/$initials' ./1.168.192.db > /var/named/1.168.192.db
sed 's/clientip/$clientip' /var/named/1.168.192.db
sed 's/serverip/$serverip' /var/named/1.168.192.db
sed 's/defaultgateway/$defaultgateway' /var/named/1.168.192.db



#now we restart bind server
systemctl restart named.service



#at this point we can set nameserver in client /etc/resolv.conf

#Test using dig command
